kind: pipeline
name: default

steps:
- name: build-structure
  image: alpine:3.8
  commands:
  - apk add make
  - make folder-structure layout-images env-file
  when:
    event:
    - push
- name: build-composer
  image: composer
  commands:
  - cd src/
  - composer install --ignore-platform-reqs --no-scripts
  when:
    event:
    - push
- name: build-npm
  image: node:8
  commands:
  - cd src/
  - npm install && node_modules/.bin/gulp --production
  when:
    event:
    - push
# - name: test-phpunit  
#   image: epcallan/php7-testing-phpunit:7.1-phpunit5

#   commands:
#   - cd src/
#   - composer install --ignore-platform-reqs --no-scripts
#   - php artisan migrate --force
#   - php artisan db:seed --force
#   - vendor/bin/phpunit
#   when:
#     event:
#     - push
- name: build-image  
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: latest
    dry_run: true
  when:
    event:
    - push
- name: test-phpunit
  image: lanopsdev/manager:latest
  environment:
    APP_KEY:
      from_secret: TEST_APP_KEY
  commands:
  - cd /web/html/
  - ls
  - php artisan migrate --force
  - php artisan db:seed --force
  - vendor/bin/phpunit
  when:
    event:
    - push
- name: push-image
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: latest
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
    - push
services:
- name: database
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: lan_manager
    MYSQL_USER: lan_manager
    MYSQL_PASSWORD: password
    MYSQL_RANDOM_ROOT_PASSWORD: true